---
- name: "Create nexus download path"
  file:
   path: "{{ item }}"
   state: directory
  with_items:
      - "{{ nexus_home }}"
      - "{{ nexus_data_dir }}"
  
- name: "Adding nexus user"
  user:
    name: nexus
    comment: Nexus Artifact Account
    shell: /bin/bash
    createhome: yes
    home: "{{ nexus_home }}"
   
- name: "Download Nexus package for Ubuntu servers from web"
  get_url:
    url: "{{ nexus_url }}"
    dest: "{{ nexus_home }}"
    force: True
    mode: 0755
  become: true

- name: "Extracting Nexus package"
  unarchive:
     src: /{{ nexus_home }}/nexus-3.17.0-01-unix.tar.gz
     dest: "{{ nexus_home }}"
     copy: no
     owner: nexus

- name: "Installing Nexus"
  shell:
      cmd: |
        cd {{ nexus_home }} && rm -rf nexus-3.17.0-01-unix.tar.gz sonatype-work 
        mv nexus-3.* nexus
        sed -i 's|#run_as_user=""|run_as_user="{{ user }}"|' ./nexus/bin/nexus.rc \
        && chown -R nexus:nexus "{{ nexus_data_dir }}"
        sed -i 's|^-Dkaraf.data=.*|-Dkaraf.data={{ nexus_data_dir }}|; s|^-Djava.io.tmpdir=.*|-Djava.io.tmpdir=data/tmp|; s|^-XX:LogFile=.*|-XX:LogFile=/nexus-data/log/jvm.log|' ./nexus/bin/nexus.vmoptions
        grep "nexus - nofile 65536" /etc/security/limits.conf  2>&1 >/dev/null || echo "nexus - nofile 65536" >> {{ conf }}
        [ ! -L /etc/init.d/nexus ] && ln -s /nexus/nexus/bin/nexus /etc/init.d/nexus
        chown -R nexus:nexus "{{ nexus_home }}"
      warn: False
  become: true

- name: "Start Nexus"
  service: name="{{ item }}" state=started enabled=true
  with_items:
     - "{{ user }}"
