- name: "Install packages in Amazon Server"
  yum: pkg="{{ item }}" state=present
  with_items:
    - git
    - wget
    - curl
    - tmux
    - dos2unix
    - sysstat
    - java-1.8.0-openjdk 
    - java-1.8.0-openjdk-devel
