---
- name: "Check current docker compose version"
  shell: "docker-compose --version"
  ignore_errors: true
  no_log: true
  register: docker_compose_current_version
- name: "Delete existing docker-compose version"
  file: path="{{ docker_compose_path }}" state=absent
  when: docker_compose_current_version.stdout != 0
- name: "Installing docker compose"
  get_url:
     url: https://github.com/docker/compose/releases/download/{{ docker_compose_version }}/docker-compose-{{ ansible_system }}-{{ ansible_userspace_architecture }}
     dest: "{{ docker_compose_path }}"
     force: True
     mode: 0755
  become: true
